changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: '🔥 Breaking Changes'
      labels:
        - 'breaking'
    - title: '🏕 Features'
      labels:
        - 'feat'
    - title: '🐛 Bug Fixes'
      labels:
        - 'fix'
    - title: '📄 Docs'
      labels:
        - 'docs'
    - title: '📦 Dependencies & Build'
      labels:
        - 'chore'
    - title: 'Other Changes'
      labels:
        - "*"
